# Generated by Django 2.2.15 on 2020-08-20 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter_app', '0002_remove_dweets_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date_commented',
        ),
        migrations.RemoveField(
            model_name='dweets',
            name='date_created',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dweets',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dweets',
            name='like',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dweets',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
