# Generated by Django 2.2.15 on 2020-08-21 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter_app', '0003_auto_20200820_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweets',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
